### ISSUE TITLE
Mod doesn't works on server 1.21.1

### ISSUE THREAD

**Issue by h0bbayt** [DarkSnakeX/LogMyBlock#5]
Mod still isn't working on server. On server startup it just crashing minecraft. Error:
java.lang.NoClassDefFoundError: com/mojang/text2speech/Narrator
	at TRANSFORMER/logmyblockneoforge@1.0.1/me.darksnakex.logmyblockneoforge.BlockEventSaveData.loadBlockEvents(BlockEventSaveData.java:61) ~[LogMyBlock.jar%23275!/:?] {re:classloading}
	at TRANSFORMER/logmyblockneoforge@1.0.1/me.darksnakex.logmyblockneoforge.LogMyBlockNeoForge.onServerStarted(LogMyBlockNeoForge.java:34) ~[LogMyBlock.jar%23275!/:?] {re:classloading}
	at MC-BOOTSTRAP/net.neoforged.bus/net.neoforged.bus.EventBus.post(EventBus.java:350) ~[bus-8.0.2.jar%2362!/:?] {}
	at MC-BOOTSTRAP/net.neoforged.bus/net.neoforged.bus.EventBus.post(EventBus.java:315) ~[bus-8.0.2.jar%2362!/:?] {}
	...

crash file included into issue. 

[crash-2025-06-14_19.03.49-server.txt](https://github.com/user-attachments/files/20738621/crash-2025-06-14_19.03.49-server.txt)

As I said this crash occurs because of undefined LOGGER instance in logmyblockneoforge.BlockEventSaveData.loadBlockEvents, so you need to create your own LOGGER instance. You can check how I fixed it there: https://github.com/DarkSnakeX/LogMyBlock/pull/3

**Comment by webbgamers** [comment]
Getting the same error on 1.21.1

**Comment by DarkSnakeX** [comment]
Also since this repository only works for the Forge version, this repository will be archived and all new changes will be made on [LogMyBlockNeoForge](https://github.com/DarkSnakeX/LogMyBlockNeoForge)

If you still have new issues please write over there. Thanks.
